### ISSUE TITLE
ERROR at end of video recording, unable to index and view in browser UI after time today morning.

### ISSUE THREAD

**Issue by morningstar2213** [yuka-friends/Windrecorder#165]
hey guys!

the winrecorder is working great, it's just it's recording now and all of a sudden ERROR at the end of file. 

that and i can't brrowser after a certain time in the UI. i even restarted Win and my laptop

it looks like this:

![image](https://github.com/yuka-friends/Windrecorder/assets/71581407/bd655934-0404-4cf2-8fd2-60d9f5732a71)
![Screenshot 2024-05-14 232512](https://github.com/yuka-friends/Windrecorder/assets/71581407/2e1572d6-ba69-4368-a5db-19eacd197ee3)

I also can't add Flag notes, or mark timestamps from the window tray. 

I can still do it in the Browser UI, but then again it won't refresh with new recordings, still stuck on the morning. 

I even changed OCRED title at end manually, but i don't think that did anything.

**Comment by Antonoko** [comment]
(😭oh no that looks buggy

Under the `cache` folder, you can find error messages why current video failed to be processed, could you please provide the content? (they looks like `LOG_ERROR_2024-04-02_21-00-10-ERROR.mp4.MD`)

Don't worry, you can use PowerToy's PowerRename to replace -ERROR with -INDEX or remove just it to let WindRecorder automatically index again. (After the bug is fixed, or just wanna give another try 

In addition, we also want to ask the following information to help debugging:
- operating system and python info (10 or 11? is it run on python 3.11
- languages installed on the system and selected OCR language (you can check in setting or execute cmd command under windrecorder directory `ocr_lib\\Windows.Media.Ocr.Cli.exe -s`

> I also can't add Flag notes, or mark timestamps from the window tray.

After clicking the menu option, does a new window appear on the taskbar? (If there is, it may be that the window that appears is positioned incorrectly.
