### ISSUE TITLE
A way to refresh database

### ISSUE THREAD

**Issue by TheUnawsomeGuy** [yuka-friends/Windrecorder#182]
Hello, I have been using this app for a few days (It's great app to review what happened for each day) but after updating to the latest version, my database gets reset and I can no longer see OCR from videos before today (10/6/2024). Manually indexing database doesn't seem to fix it. The old videos are still there in the videos folder. Thank you.

**Comment by Antonoko** [comment]
Sorry to hear this feedback, it seems that the upgrade process did something wrong. But don't worry, as long as the video file is still there, all data will not be lost! You can try the following steps to troubleshoot:
- The database depends on the username configuration. You can first check whether the .db file name prefix under `userdata/db` is consistent(like `haru_bd_YYYY-MM_wind.db`) and consistent with `"user_name"` in `userdata/config_user.json`. If not, please change `"user_name"` to the same name as before (i.e. the file prefix in the past db), then delete the db file with the wrong user prefix name, and it will automatically re-index after opening windrecorder; at the same time, just in case, you can move the temporary database with the "_TEMP_READ" suffix to the recycle bin;
- For video files, if they have been indexed to other databases by mistake, you can remove the `"-OCRED"` tag in the video file, so that windrecorder will automatically re-index it (you can use PowerRename in Microsoft's Powertoy to batch rename files and remove the "-OCRED" in them
- If the above operations do not work, you can move the db folder to the recycle bin, then remove the "-OCRED" tag from all video file names, delete config_user.json, and then re-run the install_update.bat configuration tool to reset the application. This is the last resort. Re-indexing all videos may take a super long time. If you have recorded for a long time and have a lot of video files (such as up to several months), I may not recommend doing this.

**Comment by TheUnawsomeGuy** [comment]
I've checked the db file and it seems like data before 10/6 gets wiped so I'll reindex them all back. I will report back if anything goes awry.

**Comment by TheUnawsomeGuy** [comment]
Sorry I misclicked

**Comment by Antonoko** [comment]
Sorry to hear that the database was wiped, this sounds a bit unusual.😿 Currently when performing dangerous operations on user data, the app should not delete the data directly, but move it to the recycle bin (I will check it carefully again). If your recycle bin is not automatically emptied recently, it may be worth looking for it. If there is other information worth noting, feel free to report.

**Comment by TheUnawsomeGuy** [comment]
After 24 hours, every video is now OCR'ed! (≧◡≦) Everything is going great now.
