### ISSUE TITLE
feat: Recognize multiple OCR languages ​​simultaneously

### ISSUE THREAD

**Issue by Antonoko** [yuka-friends/Windrecorder#186]
Current situation: Only one language can be specified for Windows Media OCR to recognize. In the case of multiple languages, all texts cannot be recognized. This may cause inconvenience for multilingual users or learners.

Goal: Support users to configure multiple OCR languages ​​for simultaneous recognition.

Specific implementation: Complete the integration of multilingual recognition results by executing Windows Media OCR multiple times.

User voice: https://github.com/yuka-friends/Windrecorder/discussions/168

UI reference:
![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/98efb8b5-b84a-42fe-a779-c365f7c3600d)

**Comment by Steven52065** [comment]
我觉得与其多次执行识别多种语言不如换用相对更通用的OCR程序， 识别英文没有尝试，但是识别中文的准确度稍微是有点低了，换用更准确的OCR方案直接将不同的语言一起识别出来也可能省去多次执行并整合到一起的步骤吧。  
就像这个效果：https://github.com/yuka-friends/Windrecorder/issues/18#issuecomment-1874195557  

---

Translation: I think it is better to use a relatively more general OCR program instead of executing multiple language recognition multiple times. I haven't tried recognizing English, but the accuracy of recognizing Chinese is a bit low. Using a more accurate OCR solution to directly recognize different languages ​​together may also save the steps of multiple executions and integration.    
Like this effect：https://github.com/yuka-friends/Windrecorder/issues/18#issuecomment-1874195557

**Comment by Antonoko** [comment]
> 我觉得与其多次执行识别多种语言不如换用相对更通用的OCR程序， 识别英文没有尝试，但是识别中文的准确度稍微是有点低了，换用更准确的OCR方案直接将不同的语言一起识别出来也可能省去多次执行并整合到一起的步骤吧。 

俺觉得可以，这个应该会和 OCR 改造一起做（https://github.com/yuka-friends/Windrecorder/pull/146）。不过因为 Windows 自带的 OCR 是最轻量节能和基础的方案，所以也会针对性地优化（同时考虑到对语言支持也是最全面的，用户可以任意选择微软支持的语言包来组合识别

**Comment by morningstar2213** [comment]
Upgrade your hardware lol.
Serious note. Please keep video scroll playback. 
This is prized amongst all other services being non-existent. Thanks man.

**Comment by Antonoko** [comment]
通过添加了包含 TesseractOCR 在内的第三方 OCR 引擎支持，该特性已添加。

This feature has been added by adding support for third-party OCR engines including TesseractOCR.

benchmark test: https://github.com/yuka-friends/Windrecorder/blob/main/__assets__/third_party_ocr_engine_benchmark_reference.md
