### ISSUE TITLE
request: sh file for running on linux

### ISSUE THREAD

**Issue by furllmm** [yuka-friends/Windrecorder#196]
i m linux fan
but linux is my second os

**Comment by Antonoko** [comment]
Currently this project is deeply coupled to Windows capabilities, adding cross-platform support may become a feature in the future (no guarantee, still focused on Windows for now due to lack of developer). 

You can refer to these similar alternative app, some of which are cross-platform and some are developed specifically for Linux:

https://github.com/yuka-friends/Windrecorder#:~:text=In%20addition%20to%20Windrecorder%2C%20what%20other%20tools%20provide%20similar%20functions%3F

**Comment by furllmm** [comment]
is only creating sh files are not enough to run fully functionally?
can you create sh for me if enough...

**Comment by Antonoko** [comment]
> is only creating sh files are not enough to run fully functionally? can you create sh for me if enough...

I'm afraid not.💔 many methods such as some detective APIs, path pattern, OCR recognizer, etc. are designed for Windows, so they need to be redevelop to run. If you want to force it to run, after installed Python and Poetry, you can activate the virtual environment under the path by executing `poetry shell`, and then record with `python record_screen.py` or start webui with `streamlit run webui.py`. However, there is a high probability that errors will raised due to the above reasons.

**Comment by furllmm** [comment]
:D ok
while windrecorder running, ffmpeg uses 1G ram and makes my pc alot of hot 
how can i reduce ram usage if possible?
is there lightweight alternative to windrecorder that uses less ram and records screen video 
i charging my pc like 4-5 times while windrecorder running and program is heating my pc much

**Comment by Antonoko** [comment]
> while windrecorder running, ffmpeg uses 1G ram and makes my pc alot of hot
> how can i reduce ram usage if possible?

yes, in versions 0.0.18, you can choose to use flexible screenshot mode for recording. It defaults to screenshot analysis every 3s and then synthesizing into video (can optionally config to "only when plugged in"). This method will save more resources than ffmpeg and can be traced back in real time.
![image](https://github.com/yuka-friends/Windrecorder/assets/11193477/5a334a8f-52dc-4098-a449-1dbb98071099)
