### ISSUE TITLE
Settings not saving on Win 11

### ISSUE THREAD

**Issue by Haris00911** [yuka-friends/Windrecorder#205]
Installed successfully with no errors but when I went to configure my settings, they wouldn't save after restarting Windrecorder. Tried waiting after hitting save for a while, toggling read-only, and reinstalling but no changes. I attached a screen recording in case I'm not doing something correctly.

https://github.com/user-attachments/assets/8e8165be-828c-4240-8218-e33556cd561b

OS Name	Microsoft Windows 11 Pro Insider Preview
Version	10.0.26252 Build 26252
System Type	x64-based PC
Processor	13th Gen Intel(R) Core(TM) i9-13900K, 3000 Mhz, 24 Core(s), 32 Logical Processor(s)
Name	Intel(R) UHD Graphics
Name	AMD Radeon RX 6650 XT

**Comment by Antonoko** [comment]
Thanks for the feedback! Currently, when the startup option is checked, the program may crash and become unresponsive.(https://github.com/yuka-friends/Windrecorder/issues/162) 

You can configure only the startup option first, and then modify other options separately after ensuring success. (Or manually create a shortcut for `start_app.bat` and put it in the startup folder, so that it can be automatically started at system startup)

startup folder could be under:
`C:\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`(Windrecorder will automatically detect this folder and if there is a shortcut, the startup option will be automatically checked) 

or

`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`

**Comment by Haris00911** [comment]
> You can configure only the startup option first, and then modify other options separately after ensuring success. 

Tried only doing the startup option first but it still didn't save. Tried setting all the other settings except for the startup and they successfully saved and didn't revert on startup. 

> startup folder could be under: `C:\Users\YOUR_USER_NAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

Windrecorder starts at login after following these instructions: created a shortcut to the start_app.bat and moved it to the above directory. Thank you for the help, everything else is working perfectly!
