### ISSUE TITLE
is safe to delete cache folder

### ISSUE THREAD

**Issue by furllmm** [yuka-friends/Windrecorder#235]
bec. too big (few gb per hour)

**Comment by Antonoko** [comment]
Yes, the `cache` folder can be safely deleted when windrecorder is not running. In addition, the program will automatically clean up the folder after a period of time when idle. But in terms of design, the `cache` folder itself should not grow very large quickly, could you help us investigate the folder contents to see what things take up the most capacity?

(If it refers to the `cache_screenshot` folder, it is normal to occupy a large capacity. It will temporarily store screenshots, and these cache screenshots will be automatically deleted after they are automatically merged into a smaller video. If the video fails to be automatically merged and automatically cleaned after a long period of time (like a few day), please continue to submit follow-up feedback. Thank you!

**Comment by furllmm** [comment]
in windrecorder/cache/images
its grows quickly

**Comment by furllmm** [comment]
![image](https://github.com/user-attachments/assets/16d2361d-da7e-44d8-b4f6-b7dca4b2818d)
that folder grows quickly (selected) @Antonoko

**Comment by Antonoko** [comment]
Got it! When using ffmpeg direct recording mode, the iframe folder is used to temporarily extract key frames and perform recognition. Without enabling image semantic recognition, it should be automatically cleaned up when the video is indexed (if enabled, it will be cleaned up when after embedding the image semantic in idle). Anyway, it is always safe to delete cache folder contents when windrecorder not under running (temporary key frames of iframe will be re-extracted when the video need to be indexed).

**Comment by furllmm** [comment]
k
can i access webui without python and git (wondered) @Antonoko

**Comment by furllmm** [comment]
and how to disable image semantic recognition

**Comment by Antonoko** [comment]
hii,
- webui relies on python's streamlit to run, so you may still need python environment when starting webui. git exists to be able to update the app. Since the current version may not be mature and perfect, updates may still be necessary. Of course, git is optional for actual operation. (I am considering integrating python and git together as packaged released version, so that it can be used out of the box without too much configuration. But due to my limited project management knowledge, I have not been able to promote this idea too well. still wip
- Image semantic recognition is not enabled and installed by default unless the corresponding extension module under extension is installed. If you have it installed, you can turn it off in the lab tab of the webui
